### PR TITLE
Use a sudoers.d file

### PR DESCRIPTION
**Pull request by ekohl**
This works around https://bugzilla.redhat.com/show_bug.cgi?id=1483888

### CODE REVIEW

**Comment by ekohl** [comment]
@akofink maybe you still have the CentOS 7.3 box?

**Comment by akofink** [comment]
Actually still have the 7.2 box! haha I should update my boxes.

**Comment by waldenraines** [comment]
I just tested this as well and the `vagrant up centos7-devel` finished without issue whatsoever.  Thanks @ekohl!

**Comment by chris1984** [comment]
Works for me, merging

**Comment by chris1984** [comment]
thanks @ekohl

**Pull request merged**
